"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestBaselineOfNats,
	#superclass : #PackageManifest,
	#category : #'BaselineOfNats-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfNats class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#BaselineOfNats)) #'2019-07-15T11:58:31.164259+02:00') )
]
